site_name: Adl3rAi的个人网站
site_url: https://adl3rai.github.io/Adl3rAi-mkdocs-site/
site_author: Adl3rAi
site_description: Adl3rAi的个人网站

theme:
  name: material
  palette: 
    - scheme: default 
      primary: black 
      accent: blue 
      toggle:
        icon: material/toggle-switch 
        name: 切换至夜间模式 
    - scheme: slate 
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  features:
    - navigation.tabs 
    - navigation.top 
    - navigation.indexes 
    - navigation.expand 
    - search.suggest 
    - search.highlight 
  language: zh 
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs 

repo_url: https://github.com/Adl3rAi/Adl3rAi-mkdocs-site
repo_name: Adl3rAi

copyright: Copyright &copy; 2022 Adl3rAi 

extra:
  social: 
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/34817352
      name: Bilibili | AdlerAi
    - icon: fontawesome/brands/github
      link: https://github.com/Adl3rAi
      name: GitHub | Adl3rAi

nav:
  - History:
      - The Right Side of History:
        - 0 The pursuit of happiness: history/the_right_side_of_history/note1.md
        - 1 From the Mountaintop: history/the_right_side_of_history/note2.md
      - The Great Wall of China:
        - The build-era sorted by nine garrisons: history/the_great_wall/tgw.md
  - Language:
      - German:
        - Apple:
          - Apple und iPhone: language/german/apple/text1.md
          - Apple und Foxconns Suizide: language/german/apple/text2.md   
        - Beim Bau der chinesischen Mauer:
          - I: language/german/beim_bau_der_chinesischen_mauer/text1.md
          - II: language/german/beim_bau_der_chinesischen_mauer/text2.md
        - Öko und Welt:
          - Ökostrom - was der Umwelt wirklich nutzt: language/german/oeko/text1.md
        - Politik:
          - Trägt Finnland zur Uniper-Rettung bei?: language/german/politik/text1.md

plugins:
  - search: 
      lang:
        - en
        - de
  - tags
markdown_extensions:
  - pymdownx.arithmatex: 
      generic: true
  - attr_list 
  - toc:
      permalink: true 
  - pymdownx.highlight: 
     
  - pymdownx.superfences 
  - meta
extra_javascript:
  
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 
  - mkdocs/css/no-footer.css 
  - mkdocs/css/unordered-list-symbols.css