site_name: Adl3rAi的个人网站
site_url: https://adl3rai.github.io/Adl3rAi-mkdocs-site/
site_author: Adl3rAi
site_description: Adl3rAi的个人网站

theme:
  name: material
  palette: 
    - scheme: default 
      primary: black 
      accent: blue 
      toggle:
        icon: material/toggle-switch 
        name: 切换至夜间模式 
    - scheme: slate 
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  features:
    - navigation.tabs 
    - navigation.top 
    - navigation.indexes 
    - navigation.expand 
    - search.suggest 
    - search.highlight 
  language: zh 
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs 

repo_url: https://github.com/Adl3rAi/Adl3rAi-mkdocs-site
repo_name: Adl3rAi

copyright: Copyright &copy; 2022 Adl3rAi 

extra:
  social: 
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/34817352
    #   name: Bilibili | AdlerAi
    - icon: fontawesome/brands/github
      link: https://github.com/Adl3rAi
      name: GitHub | Adl3rAi

nav:
  # - iOS-Dev:
  #     - CS193p:
  #       - Lecture 1: Getting started with SwiftUI: dev/iosstanford/lec1.md
  #       - Lecture 2: Learning more about SwiftUI: dev/iosstanford/lec2.md
  - Algorithm:
      - Data Structure:
        - Array:
          - 0 Double Pointer: algorithm/array/double.md
          - 1 Prefix Sum Array: algorithm/array/presum.md
          - 2 Difference Array: algorithm/array/diff.md
          - 3 2D Array Traverse: algorithm/array/2dtraverse.md
          - 4 Sliding Window: algorithm/array/sliding.md
          - 5 Rabin-Karp Algorithm: algorithm/array/rk.md
          - 6 Binary Search:
            - 0 Basics: algorithm/array/bs.md
            - 1 Extremum: algorithm/array/extre.md
        - Linked List:
          - 0 Single Linked List: algorithm/linked_list/single.md
          - 1 Reverse Linked List: algorithm/linked_list/reverse.md
        - Tree:
          - 0 Binary Tree Basics and Traverse: algorithm/tree/basics.md
          - 1 Binary Tree Construct: algorithm/tree/build.md
          - 2 Binary Search Tree Basics: algorithm/tree/bst_basics.md
          - 3 Sort Algorithm:
            - 0 Merge Sort: algorithm/tree/merge.md
            - 1 Quick Sort: algorithm/tree/quick.md
          - 4 Lowest Common Ancestor: algorithm/tree/lca.md
        - Design:
          - 0 Least Recently Used(LRU) cache: algorithm/design/lru.md
          - 1 Least Frequently User(LFU) cache: algorithm/design/lfu.md
          - 2 Design Twitter: algorithm/design/twi.md
  - History:
      - The Right Side of History:
        - 0 The pursuit of happiness: history/the_right_side_of_history/note1.md
        - 1 From the Mountaintop: history/the_right_side_of_history/note2.md
      - The Great Wall of China:
        - The build-era sorted by nine garrisons: history/the_great_wall/tgw.md
  - Language:
      - German:
        - Apple:
          - Apple und iPhone: language/german/apple/text1.md
          - Apple und Foxconns Suizide: language/german/apple/text2.md   
        - Beim Bau der chinesischen Mauer:
          - I: language/german/beim_bau_der_chinesischen_mauer/text1.md
          - II: language/german/beim_bau_der_chinesischen_mauer/text2.md
          - III: language/german/beim_bau_der_chinesischen_mauer/text3.md
          - IV: language/german/beim_bau_der_chinesischen_mauer/text4.md
          - V: language/german/beim_bau_der_chinesischen_mauer/text5.md
        - Öko und Welt:
          - Ökostrom - was der Umwelt wirklich nutzt: language/german/oeko/text1.md
          - Mehr Unabhängigkeit bei Kohle, Gas und Öl: language/german/oeko/text2.md
        - Kultur:
          - Über einige Merkmale westlicher Gesellschaft: language/german/kultur/text1.md
        - Politik:
          - Trägt Finnland zur Uniper-Rettung bei?: language/german/politik/text1.md
          - Wo bleibt das Machtwort des Kanzlers?: language/german/politik/text2.md
          - Merkels Geschenk: language/german/politik/text3.md
          - China nutzt Pelosi-Besuch als Vorwand: language/german/politik/text4.md
          - 16 chinesische Kampfjets überqueren die Medianlinie: language/german/politik/text5.md
          - Befürchtete Eskalation im Taiwankonflikt - deutsche Außerpolitiker warnen vor katastrophalen Folge: language/german/politik/text6.md
          - Und er kann doch lächeln: language/german/politik/text7.md
          - Wirtschaftskrieg mit China wäre teuer: language/german/politik/text8.md

plugins:
  - search: 
      lang:
        - en
        - de
  - tags
markdown_extensions:
  - pymdownx.arithmatex: 
      generic: true
  - attr_list 
  - toc:
      permalink: true 
  - pymdownx.highlight: 
     
  - pymdownx.superfences 
  - meta
extra_javascript:
  
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 
  - mkdocs/css/no-footer.css 
  - mkdocs/css/unordered-list-symbols.css